"""начальная схема

Revision ID: 59973cef0697
Revises:
Create Date: 2026-09-21 11:45:52.759540
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "59973cef0697"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_documents_content_hash"), ["content_hash"], unique=True
        )

    op.create_table(
        "debt_cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("debtor_name", sa.String(length=512), nullable=True),
        sa.Column("case_number", sa.String(length=128), nullable=True),
        sa.Column("debt_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("debt_currency", sa.String(length=3), nullable=False),
        sa.Column("make", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("vin", sa.String(length=17), nullable=True),
        sa.Column("plate", sa.String(length=16), nullable=True),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("market_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("market_value_source", sa.String(length=64), nullable=True),
        sa.Column("market_value_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("debt_to_value_ratio", sa.Float(), nullable=True),
        sa.Column("extractor", sa.String(length=32), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("fields_meta", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("debt_cases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_debt_cases_case_number"), ["case_number"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_debt_cases_debt_amount"), ["debt_amount"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_debt_cases_document_id"), ["document_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_debt_cases_make"), ["make"], unique=False)
        batch_op.create_index("ix_debt_cases_make_model", ["make", "model"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_debt_cases_market_value"), ["market_value"], unique=False
        )
        batch_op.create_index("ix_debt_cases_ratio", ["debt_to_value_ratio"], unique=False)
        batch_op.create_index(batch_op.f("ix_debt_cases_vin"), ["vin"], unique=False)
        batch_op.create_index(batch_op.f("ix_debt_cases_year"), ["year"], unique=False)

    op.create_table(
        "photos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_photos_document_id"), ["document_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_photos_document_id"))

    op.drop_table("photos")
    with op.batch_alter_table("debt_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_debt_cases_year"))
        batch_op.drop_index(batch_op.f("ix_debt_cases_vin"))
        batch_op.drop_index("ix_debt_cases_ratio")
        batch_op.drop_index(batch_op.f("ix_debt_cases_market_value"))
        batch_op.drop_index("ix_debt_cases_make_model")
        batch_op.drop_index(batch_op.f("ix_debt_cases_make"))
        batch_op.drop_index(batch_op.f("ix_debt_cases_document_id"))
        batch_op.drop_index(batch_op.f("ix_debt_cases_debt_amount"))
        batch_op.drop_index(batch_op.f("ix_debt_cases_case_number"))

    op.drop_table("debt_cases")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_content_hash"))

    op.drop_table("documents")
    # ### end Alembic commands ###
